# SPDX-FileCopyrightText: 2021 Shuai Zhang
#
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = ["NOTICE", "uv.lock"]
precedence = "override"
SPDX-FileCopyrightText = "2021 Shuai Zhang"
SPDX-License-Identifier = "Apache-2.0"
